/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Article_Skeleon: typeof import('./src/components/Skeleon/article_Skeleon/index.vue')['default']
    ArticleItem: typeof import('./src/components/HomeArticleList/components/article-item.vue')['default']
    BlogFooter: typeof import('./src/components/layout/footer/blog-footer.vue')['default']
    BlogHeader: typeof import('./src/components/layout/header/blog-header.vue')['default']
    BlogMain: typeof import('./src/components/layout/main/blog-main.vue')['default']
    Bot: typeof import('./src/components/AIBot/bot.vue')['default']
    Drawer: typeof import('./src/components/layout/widgets/drawer/drawer.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Experiment: typeof import('./src/components/layout/header/widgets/experiment/experiment.vue')['default']
    Header: typeof import('./src/components/header/header.vue')['default']
    HomeArticleList: typeof import('./src/components/HomeArticleList/home-article-list.vue')['default']
    HomeBtn: typeof import('./src/components/layout/header/widgets/home-btn/homeBtn.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Option: typeof import('./src/components/layout/header/widgets/preferences/option.vue')['default']
    Pagination: typeof import('./src/components/Pagination/pagination.vue')['default']
    Preferences: typeof import('./src/components/layout/header/widgets/preferences/preferences.vue')['default']
    RightSide: typeof import('./src/components/RightSide/right-side.vue')['default']
    RightSide_Skeleon: typeof import('./src/components/Skeleon/rightSide_Skeleon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/layout/header/widgets/global-search/search.vue')['default']
    Style: typeof import('./src/components/layout/header/widgets/optionn/style.vue')['default']
    Toggle: typeof import('./src/components/layout/header/widgets/theme-toggle/toggle.vue')['default']
    Toggle_icon: typeof import('./src/components/layout/header/widgets/stylee/toggle_icon.vue')['default']
    TypeWriter: typeof import('./src/components/TypeWriter/type-writer.vue')['default']
  }
}
